name: Build documents

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

env:
  INSTANCE: sinoseries_document.tree
  ARTIFACT: sinoseries-document.zip
  DOCKER_VERSION: 233.4797

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
          retention-days: 7

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: docs

      - name: Unzip
        run: unzip -O UTF-8 -qq ${{ env.ARTIFACT }} -d dir

      - name: Setup
        uses: actions/configure-pages@v2

      - name: Upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: dir

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
